hostname: bsky.example.org
pds:
  replicaCount: 1
  image:
    repository: ghcr.io/bluesky-social/pds
    tag: "0.4"
  containerPort: 2583
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 256Mi
  secretsName: ""
  pvc:
    storageClass: ""
    storageRequest: 20Gi
    accessModes:
      - ReadWriteOnce
  service:
    type: ClusterIP
  ingress:
    ingressClass: ""
    tls:
      enabled: true
    annotations: {}
  pdsadmin:
    enabled: true
    image: arunvelsriram/utils
    resources:
      requests:
        memory: 20Mi
        cpu: 5m
      limits:
        memory: 20Mi