{{ if .Values.pds.pdsadmin.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-pds-bin"
data:
  pdsadmin: |
    #!/bin/bash
    set -o errexit
    set -o nounset
    set -o pipefail

    PDSADMIN_BASE_URL="https://raw.githubusercontent.com/bluesky-social/pds/main/pdsadmin"

    # Command to run.
    COMMAND="${1:-help}"
    shift || true

    # Download the script, if it exists.
    SCRIPT_URL="${PDSADMIN_BASE_URL}/${COMMAND}.sh"
    SCRIPT_FILE="$(mktemp /tmp/pdsadmin.${COMMAND}.XXXXXX)"

    if ! curl --fail --silent --show-error --location --output "${SCRIPT_FILE}" "${SCRIPT_URL}"; then
      echo "ERROR: ${COMMAND} not found"
      exit 2
    fi

    chmod +x "${SCRIPT_FILE}"
    if "${SCRIPT_FILE}" "$@"; then
      rm --force "${SCRIPT_FILE}"
    fi
{{ end }}